//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJournal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lessons
    {
        public int LessId { get; set; }
        public int TeacherId { get; set; }
        public string Theme { get; set; }
        public int Edu { get; set; }
        public System.DateTime DateLess { get; set; }
        public Nullable<bool> State { get; set; }
        public int GroupId { get; set; }
        public string HomeWork { get; set; }
    
        public virtual EduSubjects EduSubjects { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
