//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJournal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks
    {
        public int LessId { get; set; }
        public int StudentId { get; set; }
        public Nullable<int> Mark { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Activity { get; set; }
        public Nullable<bool> Presence { get; set; }
    }
}
