//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJournal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int StudentId { get; set; }
        public int GroupId { get; set; }
        public System.DateTime ReceiptDate { get; set; }
    
        public virtual StGroup StGroup { get; set; }
        public virtual Users Users { get; set; }
    }
}
